### ISSUE TITLE
2주차 - 기본키매핑 - sequence : call next value 2번 호출되는 이유?

### ISSUE THREAD

**Issue by heewonham** [SogangSpring/JPAStudy#13]
기본키 매핑에서 sequence 전략을 선택하고 allocation size 가 50인 경우, 
처음 DB의 시퀸스를 호출할 때 1 이 나오기 위해서 초기 설정은 아래와 같이 되어있다.
         현재 값 : -49

한 member를 persist할 경우,
call next value가 두 번 호출되는데 ,, 
처음 호출을 통해 DB SEQ값은 1이 되고, 그 다음 호출을 통해 DB SEQ 값은 51이 된다.

한꺼번에 50으로 호출하지 않고 call next value를 2번 호출하는 이유 무엇일까요?

**Comment by TaeBeomShin** [comment]
This is just a guess, but recent versions of Hibernate use a hi/lo generator rather than a plain sequence generator by default. Perhaps the generator initializes itself with two calls in order to double-check the increment or something? If so you should be able to insert 49 additional accounts before the sequence is used next time. If you prefer to use plain sequences, add allocationSize=1 to the SequenceGenerator annotation.
